common:
    arch: FeatherNetB
    workers: 1
    batch_size: 32
    epochs: 150
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/feathernetB_bs32
