common:
    arch: FeatherNetA
    workers: 1
    batch_size: 32
    epochs: 200
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/FeatherNetA_bs32
