common:
    arch: MobileLiteNet54_se
    workers: 1
    batch_size: 64
    epochs: 200
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/MobileLiteNet54-se_bs64
